# config-repo/gateway-service.yml
server:
  port: 9090

spring:
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**


jwt:
  secret: myVerySecureSecretKeyThatIsAtLeast32CharactersLong123456789
