# config-repo/gateway-service.yml
server:
  port: 9090

spring:
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**


jwt:
  secret: myVerySecureSecretKeyThatIsAtLeast32CharactersLong123456789

# Disable Eureka
eureka:
  client:
    enabled: false