# Server Configuration
server:
  port: 8082

spring:
  application:
    name: auth-service
#  cloud:
#    config:
#      enabled: false

# JWT Configuration
jwt:
  secret: myVerySecureSecretKeyThatIsAtLeast32CharactersLong123456789
  expiration: 86400000 # 24 hours in milliseconds

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
#    enabled: false
#    register-with-eureka: false
#    fetch-registry: false

# Logging Configuration for debugging
logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

