spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/