# application.yml
server:
  port: 9090

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/


