# application.yml
spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
