# application.yml
server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///E:/microservice/config-repo
          default-label: main
  profiles:
    active: native

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/